# Generated by Django 2.0.2 on 2019-03-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_game',
            field=models.BooleanField(default=False),
        ),
    ]
