# Generated by Django 2.0.2 on 2019-03-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_users', '0002_user_in_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ask', 'ask'), ('guess', 'guess')], max_length=100, null=True),
        ),
    ]
