# Generated by Django 2.0.2 on 2019-03-04 13:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guessedword', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuessedAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guessedanswer', models.CharField(blank=True, max_length=500, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('guessedword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guessedword.GuessedWord')),
            ],
            options={
                'verbose_name_plural': 'GuessedAnswer',
            },
        ),
        migrations.CreateModel(
            name='YesNoQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('responded', models.BooleanField(default=False)),
                ('response', models.CharField(blank=True, max_length=5, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('guessedword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guessedword.GuessedWord')),
            ],
            options={
                'verbose_name_plural': 'YesNoQuestion',
            },
        ),
    ]
