# Generated by Django 2.0.2 on 2019-03-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yesnoquestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yesnoquestion',
            name='response',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=5, null=True),
        ),
    ]
