# Generated by Django 2.0.2 on 2019-03-04 13:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all_users', '0002_user_in_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuessedWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('asker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asker', to='all_users.User')),
                ('guesser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guesser', to='all_users.User')),
            ],
            options={
                'verbose_name_plural': 'GuessedWord',
            },
        ),
    ]
