# Generated by Django 2.0.2 on 2019-03-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessedword', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guessedword',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
