# Generated by Django 2.0.2 on 2019-03-12 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_users', '0003_auto_20190306_1625'),
        ('guessedword', '0002_guessedword_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='guessedword',
            name='ended_asker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guessedword',
            name='ended_guesser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guessedword',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='all_users.User'),
        ),
    ]
